In [22]:
import pandas as pd

In [23]:
file_path = r"C:\Users\thomm\Documents\GitHub\modelacion-y-simulacion-5\proyecto-final-prebel\bases-de-datos\datos-discretos.xlsx"
df = pd.read_excel(file_path)

In [24]:
df

,id,Paro Produccion,Centro de Trabajo,Evento,Turno,Fecha Turno,AÃ±o,Mes,Fecha Inicio,Fecha Fin,...,Turno 2,Turno 3,Id Centro,F Tiempo,Id Variables,semana,F Conversion Real,Cant.Operarios,Codigo Paro,Consumo de Energia
0,534776,0,E47,Cambio Turno,3,2022-12-31,2023,Enero,2022-12-31 22:00:03.353,2023-01-01 06:00:02.123,...,0.000,479.983,29,1.0,28694,1,0,0,NaN,0
1,534778,0,E46,Cambio Turno,3,2022-12-31,2023,Enero,2022-12-31 22:00:03.353,2023-01-01 06:00:02.123,...,0.000,479.983,28,1.0,28730,1,0,0,NaN,0
2,534801,0,E47,Cambio Turno,3,2022-12-31,2023,Enero,2022-12-31 22:00:03.353,2023-01-01 06:00:02.120,...,0.000,479.983,29,1.0,28694,1,0,0,NaN,0
3,534803,0,E46,Cambio Turno,3,2022-12-31,2023,Enero,2022-12-31 22:00:03.353,2023-01-01 06:00:02.120,...,0.000,479.983,28,1.0,28730,1,0,0,NaN,0
4,534815,0,4BOQUILLAS,Cambio Turno,3,2022-12-31,2023,Enero,2022-12-31 22:00:03.353,2023-01-01 06:00:02.123,...,0.000,479.983,31,1.0,28822,1,0,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109558,1127744,0,ACCUROFILL2,Cambio Turno,2,2023-12-31,2023,Diciembre,2023-12-31 14:00:16.523,2023-12-31 22:00:09.957,...,479.883,0.000,22,1.0,54405,53,0,0,NaN,0
109559,1127745,0,ACCUROFILL1,Cambio Turno,2,2023-12-31,2023,Diciembre,2023-12-31 14:00:16.523,2023-12-31 22:00:09.957,...,479.883,0.000,21,1.0,54410,53,0,0,NaN,0
109560,1127749,0,E48,Cambio Turno,2,2023-12-31,2023,Diciembre,2023-12-31 14:00:16.523,2023-12-31 22:00:09.957,...,479.883,0.000,30,1.0,54412,53,0,0,NaN,0
109561,1127750,0,ACCUROFILL1,Cambio Turno,2,2023-12-31,2023,Diciembre,2023-12-31 14:00:16.523,2023-12-31 22:00:09.957,...,479.883,0.000,21,1.0,54410,53,0,0,NaN,0
109562,1127752,0,E48,Cambio Turno,2,2023-12-31,2023,Diciembre,2023-12-31 14:00:16.523,2023-12-31 22:00:09.957,...,479.883,0.000,30,1.0,54412,53,0,0,NaN,0

In [40]:
# Initialize an empty list to keep track of non-repeated 'Orden'
ordenes = []

# Loop through the 'Orden' column and collect non-repeated values
for i in range(len(df['T Intervalo'])):
    if df['Orden'][i] not in ordenes:
        ordenes.append(df['Orden'][i])

# Create a dictionary from the list of non-repeated 'Orden'
ordenes_dict = {orden: 0 for orden in ordenes}
ordenes = ordenes[1:]

In [41]:
for i in range(len(df['T Intervalo'])):
    orden = df['Orden'][i]
    intervalo = df['T Intervalo'][i]

    ordenes_dict[orden] += intervalo

del ordenes_dict['0']

In [42]:
tiempos_cook = []
for orden in ordenes:
    tiempos_cook.append(ordenes_dict[orden])

[301.177,
 393.90299999999996,
 177.444,
 935.5089999999998,
 338.581,
 341.024,
 533.3359999999999,
 676.9920000000003,
 1106.9509999999998,
 344.368,
 711.628,
 701.118,
 545.1669999999999,
 2735.6040000000003,
 340.57100000000014,
 352.0979999999999,
 336.5600000000001,
 457.16600000000017,
 223.55499999999998,
 375.296,
 339.45399999999995,
 118.98499999999999,
 384.9009999999999,
 565.353,
 172.61499999999998,
 679.4409999999999,
 367.988,
 510.5270000000001,
 1510.4709999999998,
 91.796,
 376.6170000000001,
 342.233,
 155.476,
 287.58400000000006,
 298.95399999999995,
 495.85999999999996,
 743.8439999999998,
 794.4789999999999,
 1883.7529999999997,
 776.1319999999998,
 375.177,
 714.781,
 582.7520000000001,
 512.372,
 611.3109999999999,
 1071.719,
 932.054,
 1010.6300000000001,
 473.75700000000006,
 413.738,
 426.69199999999995,
 245.483,
 405.73,
 592.2659999999998,
 432.27199999999993,
 565.4030000000001,
 208.627,
 671.2559999999999,
 645.8359999999999,
 463.23,
 271.981,
 1492.5620000000004,
 1586.4710000000005,
 459.799,
 593.8149999999999,
 481.095,
 247.955,
 703.7460000000002,
 326.1310000000001,
 998.8330000000002,
 210.36699999999996,
 258.806,
 363.88899999999995,
 657.866,
 353.10299999999995,
 379.9,
 391.99600000000004,
 625.9939999999999,
 545.738,
 1255.8049999999998,
 175.993,
 538.57,
 302.25300000000004,
 300.375,
 454.08300000000014,
 740.9940000000001,
 937.669,
 485.34799999999996,
 301.704,
 851.93,
 389.96799999999996,
 3545.585,
 309.083,
 450.26199999999994,
 3168.5359999999996,
 2930.9649999999997,
 630.9339999999999,
 166.25600000000003,
 365.13299999999987,
 453.7569999999999,
 1203.3370000000002,
 532.0049999999999,
 231.63299999999995,
 276.65599999999995,
 614.5579999999998,
 1629.169,
 632.7859999999997,
 545.1289999999999,
 1124.2210000000002,
 898.2079999999997,
 775.1870000000001,
 415.28199999999987,
 556.6469999999999,
 764.1819999999996,
 506.69499999999994,
 478.487,
 357.2540000000001,
 867.9709999999999,
 315.43999999999994,
 482.29800000000006,
 334.407,
 551.797,
 569.6129999999998,
 689.415,
 1003.0590000000002,
 455.35099999999994,
 695.4839999999998,
 446.831,
 583.9570000000001,
 431.653,
 530.754,
 481.4440000000001,
 169.76700000000002,
 414.02399999999994,
 235.42999999999998,
 636.9470000000002,
 1011.197,
 402.79799999999994,
 826.5390000000001,
 4401.424000000001,
 230.38300000000004,
 3804.9410000000003,
 501.6389999999999,
 1062.9400000000003,
 392.932,
 722.8149999999999,
 310.16200000000003,
 1103.2589999999998,
 578.9970000000001,
 279.99399999999997,
 1254.247,
 527.0469999999999,
 1376.0580000000004,
 772.14,
 3972.787,
 724.6569999999999,
 463.67500000000007,
 842.8659999999999,
 467.70199999999994,
 692.782,
 503.319,
 453.128,
 889.0459999999996,
 1069.678,
 866.189,
 691.068,
 282.204,
 276.88199999999995,
 1444.8070000000002,
 373.71299999999997,
 1544.3230000000015,
 946.834,
 706.6,
 421.13000000000005,
 402.85400000000004,
 404.764,
 817.2630000000003,
 983.91,
 922.5180000000003,
 199.53,
 288.20700000000005,
 681.4820000000002,
 728.1229999999999,
 354.0700000000001,
 564.604,
 829.2759999999998,
 224.21300000000002,
 447.3690000000001,
 452.6990000000001,
 1330.7319999999995,
 316.065,
 1245.5169999999998,
 521.1959999999999,
 663.974,
 1131.8279999999995,
 538.042,
 549.8389999999998,
 309.268,
 862.0600000000001,
 389.64099999999996,
 452.2189999999999,
 523.4730000000001,
 402.7149999999998,
 660.7390000000001,
 599.0490000000001,
 1562.6400000000006,
 519.176,
 1715.1140000000007,
 584.2059999999999,
 1468.711000000001,
 455.317,
 382.646,
 750.4489999999996,
 959.6999999999999,
 574.3580000000002,
 431.57599999999996,
 882.3839999999999,
 482.04300000000006,
 1.801,
 697.6389999999999,
 454.83199999999994,
 316.56,
 477.91100000000006,
 240.17399999999995,
 512.6469999999999,
 522.7810000000001,
 319.3310000000001,
 3690.5199999999995,
 3236.2509999999997,
 2366.0090000000005,
 1456.9979999999996,
 598.051,
 505.2379999999999,
 687.159,
 1169.9330000000002,
 1122.347,
 866.4639999999998,
 107.011,
 828.596,
 620.0009999999999,
 599.8659999999998,
 1616.7779999999996,
 296.95699999999994,
 1135.376,
 376.86799999999994,
 1291.5830000000003,
 1312.1359999999995,
 985.0360000000002,
 552.543,
 626.407,
 481.173,
 139.11599999999996,
 577.8500000000001,
 786.1750000000001,
 935.4130000000004,
 756.3050000000001,
 4576.326999999999,
 179.77999999999997,
 640.9000000000002,
 324.36800000000005,
 477.4959999999999,
 1333.2590000000007,
 364.1,
 343.0610000000001,
 1165.8040000000005,
 231.77900000000002,
 907.4549999999998,
 400.89200000000017,
 598.9390000000002,
 419.40399999999994,
 1404.4549999999997,
 287.3589999999999,
 1031.794,
 925.338,
 501.79900000000004,
 1397.6899999999998,
 362.72800000000007,
 525.979,
 289.28799999999995,
 739.4810000000001,
 678.2249999999999,
 323.5059999999999,
 690.6089999999998,
 600.535,
 142.58100000000005,
 78.05,
 1127.3729999999998,
 584.634,
 508.4879999999999,
 396.849,
 783.3469999999998,
 203.106,
 417.91799999999995,
 1214.2580000000005,
 219.72899999999998,
 2141.027999999999,
 1114.6490000000001,
 576.5939999999998,
 570.441,
 494.66799999999995,
 275.303,
 1467.7820000000006,
 1383.0030000000002,
 1935.292,
 664.7049999999999,
 643.116,
 3229.8470000000007,
 2875.168999999999,
 726.823,
 455.53299999999996,
 341.687,
 799.2019999999998,
 4126.599,
 516.9569999999998,
 350.639,
 146.518,
 788.019,
 411.916,
 502.81299999999993,
 476.453,
 487.5280000000001,
 657.352,
 1585.985,
 171.54700000000003,
 475.2660000000001,
 627.1069999999999,
 252.95,
 427.4839999999999,
 318.459,
 170.526,
 401.5750000000001,
 232.557,
 853.7069999999995,
 1082.4469999999997,
 616.396,
 558.9259999999997,
 473.2759999999999,
 1356.6579999999994,
 343.522,
 676.956,
 504.93599999999986,
 706.4230000000002,
 5246.981,
 253.70900000000003,
 1067.1219999999998,
 196.29600000000008,
 4116.810000000002,
 387.9200000000001,
 984.6449999999998,
 1447.2590000000002,
 219.64399999999992,
 782.1969999999999,
 75.827,
 111.0,
 864.5119999999995,
 270.70500000000004,
 338.112,
 356.765,
 480.541,
 969.469,
 979.2279999999996,
 728.119,
 315.921,
 297.56500000000005,
 694.106,
 328.9660000000001,
 835.3019999999995,
 631.057,
 548.0640000000001,
 556.4720000000001,
 317.0639999999999,
 504.856,
 2458.5509999999995,
 616.0699999999999,
 2013.5590000000007,
 749.9119999999999,
 1425.9419999999998,
 1698.7040000000009,
 1856.775,
 198.91400000000004,
 610.1650000000003,
 223.7249999999999,
 497.04600000000005,
 1052.474,
 361.682,
 325.87800000000004,
 710.1950000000002,
 810.7049999999997,
 399.43899999999996,
 685.1650000000002,
 776.8630000000002,
 459.0770000000001,
 1317.8379999999997,
 462.94599999999997,
 412.73300000000006,
 704.4169999999999,
 879.3800000000001,
 677.0369999999999,
 229.58599999999996,
 496.6219999999999,
 474.0169999999999,
 391.895,
 786.6859999999997,
 319.481,
 467.414,
 919.2219999999999,
 143.76700000000002,
 528.4510000000004,
 669.4980000000002,
 640.2260000000001,
 542.834,
 493.5919999999999,
 174.199,
 447.38499999999993,
 253.47400000000005,
 473.15,
 430.9349999999999,
 449.013,
 462.6270000000001,
 262.6259999999999,
 257.32399999999996,
 908.3439999999997,
 225.38099999999997,
 364.0220000000001,
 492.416,
 495.14200000000017,
 360.4640000000001,
 377.663,
 252.18699999999995,
 236.45100000000002,
 379.883,
 12358.166999999987,
 232.8909999999999,
 853.8609999999999,
 652.0590000000001,
 500.90499999999986,
 1137.7429999999997,
 290.425,
 350.434,
 121.07700000000003,
 1498.4780000000003,
 491.101,
 616.4789999999998,
 331.27200000000005,
 566.8380000000001,
 592.6890000000002,
 467.3280000000001,
 367.18000000000006,
 568.8789999999996,
 1.283,
 709.1109999999999,
 518.8899999999999,
 1149.6260000000002,
 159.353,
 424.208,
 253.574,
 186.85,
 546.2730000000003,
 304.68200000000013,
 564.3319999999999,
 273.25,
 1315.874,
 448.78199999999987,
 300.4420000000001,
 294.75300000000004,
 513.117,
 807.7710000000001,
 415.99899999999997,
 340.69100000000003,
 278.32,
 840.678,
 225.271,
 339.70899999999995,
 387.804,
 310.7220000000001,
 401.27399999999994,
 903.5190000000003,
 235.899,
 265.721,
 396.13899999999995,
 5659.950999999996,
 829.225,
 112.00800000000001,
 551.016,
 3475.230999999999,
 559.519,
 354.56999999999994,
 362.588,
 359.977,
 612.8610000000002,
 309.60300000000007,
 217.35400000000004,
 509.2090000000001,
 1.783,
 455.725,
 555.2689999999999,
 290.99900000000014,
 599.5769999999999,
 472.26599999999985,
 578.21,
 281.323,
 637.793,
 191.233,
 407.467,
 252.268,
 471.668,
 134.07799999999995,
 478.98700000000014,
 108.03200000000001,
 658.9430000000003,
 122.21399999999998,
 341.20300000000003,
 449.55199999999985,
 273.22900000000004,
 78.89099999999999,
 641.4189999999999,
 328.76500000000004,
 249.50700000000003,
 1016.761,
 222.50699999999992,
 772.6330000000002,
 289.20900000000006,
 793.719,
 628.6199999999998,
 133.99300000000002,
 701.3990000000001,
 1020.0910000000005,
 1040.552,
 214.942,
 322.39599999999996,
 377.26599999999996,
 318.6599999999999,
 1955.5530000000003,
 581.2679999999999,
 794.6069999999997,
 550.535,
 1149.187,
 430.675,
 187.007,
 1469.6380000000001,
 160.09500000000003,
 481.592,
 126.58100000000002,
 1493.635,
 387.35900000000004,
 724.0139999999997,
 155.433,
 368.20300000000003,
 183.03799999999998,
 22.317,
 495.03800000000007,
 373.2770000000001,
 739.4300000000001,
 309.72400000000005,
 4525.151,
 964.5699999999996,
 552.9100000000001,
 308.16299999999995,
 506.919,
 775.4399999999999,
 531.025,
 1344.2000000000003,
 301.819,
 334.064,
 400.071,
 479.02899999999994,
 734.4309999999997,
 411.41100000000006,
 284.426,
 303.24199999999996,
 265.91999999999996,
 981.12,
 1292.2950000000003,
 514.269,
 101.03399999999999,
 351.546,
 253.68300000000005,
 256.55899999999997,
 221.63900000000004,
 309.20299999999986,
 444.893,
 1158.895,
 1667.1689999999999,
 316.8060000000001,
 742.884,
 721.0160000000001,
 908.5139999999993,
 1312.4359999999997,
 613.333,
 558.535,
 345.66099999999994,
 461.5669999999999,
 1004.8600000000001,
 272.0670000000001,
 368.6460000000001,
 515.06,
 218.37599999999998,
 554.545,
 209.06900000000002,
 4086.2149999999992,
 228.67800000000003,
 206.31300000000005,
 238.299,
 304.8669999999999,
 59.684,
 1600.5620000000001,
 552.485,
 107.077,
 557.245,
 629.582,
 1693.9589999999996,
 546.372,
 147.097,
 300.8840000000002,
 432.40799999999996,
 407.49500000000006,
 376.33900000000006,
 680.0790000000002,
 478.54499999999996,
 388.92699999999996,
 712.0439999999998,
 752.2839999999999,
 255.91500000000002,
 628.3549999999999,
 311.8399999999999,
 371.184,
 552.958,
 1194.2740000000001,
 912.671,
 886.9700000000004,
 643.033,
 523.885,
 692.9889999999998,
 560.907,
 530.0440000000001,
 517.519,
 585.825,
 271.869,
 609.9440000000001,
 453.105,
 127.416,
 337.782,
 308.359,
 207.66699999999997,
 262.30100000000004,
 136.87599999999998,
 586.0629999999999,
 300.25000000000006,
 453.5109999999999,
 237.94000000000003,
 564.4949999999998,
 321.02700000000004,
 160.567,
 144.331,
 480.473,
 183.95,
 1606.2339999999997,
 943.4999999999998,
 458.77399999999983,
 581.2520000000001,
 1092.1069999999997,
 497.487,
 244.07400000000004,
 184.37099999999998,
 287.414,
 347.534,
 125.471,
 288.35800000000006,
 1367.2230000000006,
 477.4950000000001,
 661.015,
 181.35600000000005,
 367.499,
 201.61599999999996,
 520.041,
 480.7389999999998,
 653.649,
 352.18,
 1049.6539999999993,
 558.3199999999999,
 644.4509999999998,
 802.6540000000001,
 826.5989999999998,
 749.7949999999998,
 813.6939999999998,
 291.562,
 1409.2119999999998,
 946.2610000000001,
 1481.1509999999998,
 704.6910000000003,
 1764.534,
 500.355,
 1551.8229999999999,
 183.236,
 547.3570000000002,
 826.0830000000003,
 559.3169999999999,
 377.62600000000003,
 489.08999999999986,
 208.763,
 226.70100000000002,
 294.329,
 140.044,
 129.6,
 131.46599999999998,
 719.25,
 326.596,
 1012.5160000000003,
 968.039,
 1397.612,
 531.4399999999999,
 791.5260000000002,
 1484.616000000001,
 542.3280000000001,
 616.945,
 419.7990000000001,
 733.882,
 458.9990000000001,
 533.328,
 314.945,
 492.89400000000006,
 299.706,
 808.1090000000003,
 441.04100000000017,
 748.1440000000002,
 1045.0649999999998,
 310.898,
 449.8749999999999,
 327.432,
 1398.0679999999998,
 479.9360000000001,
 175.697,
 520.2970000000001,
 515.4730000000001,
 1740.7699999999993,
 759.4900000000002,
 408.2969999999999,
 887.717,
 499.244,
 403.2429999999999,
 181.7,
 126.454,
 494.0140000000001,
 725.2770000000002,
 443.60600000000005,
 567.029,
 957.1579999999999,
 473.487,
 189.655,
 265.63199999999995,
 278.515,
 906.4390000000001,
 430.45899999999995,
 368.21,
 515.8870000000001,
 237.94600000000003,
 508.1500000000001,
 477.70799999999986,
 270.08799999999997,
 437.78800000000007,
 285.346,
 420.69,
 683.768,
 606.717,
 651.9730000000002,
 726.3859999999999,
 728.4120000000001,
 1305.2630000000001,
 590.666,
 930.3619999999997,
 309.06199999999995,
 351.6769999999999,
 727.0580000000001,
 879.7560000000003,
 798.164,
 892.97,
 787.5040000000004,
 978.297,
 566.39,
 838.858,
 534.1119999999999,
 471.81100000000004,
 404.74899999999997,
 979.4389999999999,
 438.3180000000001,
 596.423,
 286.762,
 314.247,
 602.4220000000003,
 142.299,
 1642.3650000000002,
 456.05099999999993,
 713.716,
 699.8799999999999,
 1025.44,
 568.1539999999999,
 738.616,
 426.227,
 3064.4889999999996,
 369.70699999999994,
 241.335,
 190.73299999999998,
 83.046,
 1696.4140000000002,
 561.7790000000001,
 404.503,
 555.317,
 266.59700000000004,
 381.59900000000005,
 1156.8199999999995,
 630.1810000000003,
 263.402,
 411.1410000000001,
 379.853,
 479.7380000000001,
 748.6779999999998,
 796.4229999999999,
 260.206,
 1379.9870000000003,
 318.99199999999996,
 374.2130000000001,
 364.427,
 354.87699999999995,
 604.9830000000001,
 1580.0660000000007,
 1353.5740000000005,
 1437.959,
 1607.550999999999,
 670.994,
 964.6589999999998,
 1035.5910000000001,
 431.2400000000001,
 265.117,
 653.6390000000001,
 873.3629999999999,
 1246.9789999999996,
 387.55299999999994,
 921.682,
 126.299,
 1009.3770000000002,
 920.8500000000001,
 920.3299999999997,
 1608.5170000000012,
 331.0840000000001,
 884.196,
 318.724,
 1685.071,
 284.71500000000003,
 832.0359999999997,
 735.1940000000001,
 603.8140000000001,
 350.214,
 343.1850000000001,
 633.2070000000001,
 443.3010000000001,
 966.4840000000005,
 689.2940000000001,
 650.446,
 931.7010000000001,
 933.238,
 604.2239999999998,
 404.3480000000001,
 200.323,
 273.761,
 706.763,
 2884.8300000000004,
 417.619,
 434.31399999999985,
 116.34000000000003,
 876.4630000000004,
 1111.2339999999997,
 146.552,
 364.21600000000007,
 570.985,
 965.2020000000002,
 294.9609999999999,
 1487.4109999999991,
 601.7020000000001,
 493.075,
 806.4820000000003,
 929.4819999999996,
 602.24,
 202.65199999999996,
 296.00699999999995,
 1057.054,
 539.576,
 922.9079999999997,
 685.1350000000001,
 659.3169999999998,
 619.0019999999998,
 411.57500000000005,
 1722.761,
 647.1490000000001,
 147.533,
 244.67299999999992,
 508.2710000000002,
 898.9489999999998,
 332.8689999999999,
 351.481,
 535.9499999999998,
 615.646,
 334.46700000000004,
 468.93000000000006,
 343.189,
 527.1460000000002,
 718.929,
 682.661,
 1078.0109999999997,
 417.875,
 2433.117000000001,
 202.42699999999994,
 284.029,
 422.473,
 726.0889999999999,
 269.9129999999999,
 1600.2959999999998,
 573.803,
 538.813,
 1668.538,
 983.9400000000002,
 429.25199999999995,
 1486.5849999999998,
 3.067,
 1452.5029999999986,
 524.1399999999999,
 203.59999999999997,
 215.11799999999997,
 378.328,
 608.8040000000002,
 222.50900000000004,
 608.8910000000001,
 362.7820000000001,
 365.2979999999999,
 438.952,
 1225.6590000000003,
 210.984,
 90.58300000000001,
 221.36999999999998,
 604.0400000000002,
 566.96,
 679.9389999999999,
 466.7840000000001,
 141.85000000000002,
 41.416999999999994,
 34.084,
 227.54700000000003,
 83.403,
 196.72199999999998,
 545.4609999999999,
 556.065,
 921.6389999999999,
 688.4579999999999,
 24.195999999999998,
 91.683,
 45.983,
 187.66599999999997,
 573.8800000000003,
 1403.1219999999994,
 495.48599999999993,
 3339.88,
 859.108,
 420.108,
 469.17600000000004,
 1233.8519999999999,
 1585.1549999999997,
 496.7010000000001,
 337.64399999999995,
 131.827,
 177.28300000000002,
 824.0020000000002,
 710.9080000000001,
 268.64199999999994,
 495.44399999999996,
 424.417,
 223.52099999999993,
 254.83100000000002,
 575.244,
 706.895,
 229.891,
 1134.181,
 1500.3750000000002,
 1066.5489999999998,
 84.699,
 44.583,
 530.542,
 544.5999999999999,
 950.2269999999997,
 386.67699999999996,
 1908.2660000000008,
 536.7369999999997,
 75.25100000000002,
 1088.0149999999999,
 655.7740000000001,
 1279.1299999999992,
 894.79,
 210.38300000000004,
 457.54600000000005,
 394.023,
 1370.077,
 289.976,
 ...]

In [ ]:
df.to_excel('output.xlsx', index=False)